name: Android CI
on: #[pull_request, push]
  push:
    branches-ignore:
      - feature/test
  pull_request:
    branches-ignore:
      - feature/test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew buildDebug
      - name: Unit tests
        id: tests
        run: ./gradlew testDebug
      - name: Instrumented tests
        id: tests
        run: ./gradlew connectedDebugAndroidTest
