name: Android CD
on:
  workflow_run:
    workflows: ["Android CI"]
    branches: [main]
    types:
      - completed
jobs:
  PlayStore:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build Release AAB
        id: buildRelease
        run: ./gradlew bundleRelease
      - name: Sign AAB
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEY_STORE_FILE }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
      - name: check de aab file
          run: ls app/build/outputs/bundle/release
#      - name: Upload AAB
#        id: uploadArtifact
#        uses: actions/upload-artifact@v1
#        with:
#          name: app
#          path: app/build/outputs/bundle/release/app-release.aab
      - name: Deploy to Play Store (Alpha)
        id: deploy
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJson: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: es.algoritmo.githubactions
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
          track: alpha
          whatsNewDirectory: whatsnew/
