name: Android CD
on:
  workflow_run:
    workflows: ["Android CI"]
    branches: [main]
    types:
      - completed
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo Hello, world!