name: Android CI
on: #[pull_request, push]
  push:
    branches:
      - 'develop'   # matches develop
      - 'feature/*' # matches every branch that begins with 'feature/'
  pull_request:
    branches:
      - 'develop'   # matches develop
      - 'feature/*' # matches every branch that begins with 'feature/'
jobs:
  ci-job-build-and-test:
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Lint
        run: ./gradlew lintDebug

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2 # https://github.com/ReactiveCircus/android-emulator-runner
        with:
          api-level: 29
          script: ./gradlew jacocoTestReport

      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: app/build/reports

  ci-job-generate-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Create APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: myapk
          path: app/build/outputs/apk/debug/app-debug.apk




#      - name: SonarQube Analysis
#        run: ./gradlew jacocoTestReport

#      - name: Kiuwan Baseline Analysis # https://github.com/marketplace/actions/kiuwan-baseline-analysis
#        uses: lsacera/KiuwanBaselineAction@v1.0
#        with:
#          # Name of Kiuwan project
#          project: Personalblog
#          # Label for the analysis
#          label: version
#          # Username for kiuwan platform
#          userid: ${{ secrets.KIUWAN_USER }}
#          # Password for kiuwan platform
#          password: ${{ secrets.KIUWAN_PASS }}
