name: Android CD
on:
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  PlayStore-job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Checkout Master branch
        run: |
          git branch
          git checkout master

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Sign AAB
        id: sign_app
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEY_STORE_FILE }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Deploy to Play Store (Alpha)
        uses: r0adkll/upload-google-play@v1.0.15
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: es.algoritmo.githubactions
          releaseFiles: ${{steps.sign_app.outputs.signedReleaseFile}}
          track: alpha
          whatsNewDirectory: whatsnew/

      - name: Push new Tag
        run: |
          TAG_NAME="$(./gradlew :app:printVersionName -q)"
          git config --global user.email "mycicd@ralgoritmo.com"
          git config --global user.name "mycicd"
          git tag -a "$TAG_NAME" -m "New version generated by Github Actions"
          git push origin $TAG_NAME


#      - name: Increment Version Code
#        run: ./gradlew incrementVersionCode
#          git add --all
#          git commit -m "New $TAG_NAME version"
#          git push origin master --force