name: Android CI
on: [pull_request, push]
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
  build:
    needs: clone
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: ls -la
      - name: Build the app
        run: ./gradlew build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Unit tests
        id: tests
        run: ./gradlew test