name: Multiple dependant jobs example
on:
  push:
    branches: [ feature/multiplejobs ]
  pull_request:
    branches: [ feature/multiplejobs ]
jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
    - name: Create artifact
      run: echo "Hello, I'm produced by firstJob" > myArtifact.txt
    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact_job1
        path: myArtifact.txt
  secondJob:
    needs: firstJob
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve saved Artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact_job1
          path: artifact
      - name: Unzip artifact
        run: unzip artifact
      - name: Modify the artifact
        run: echo "Hello, I have been changed by secondJob" >> artifact.txt
      - name: Upload the artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact_job2.txt
          path: artifact.txt
  thirdJob:
    needs: secondJob
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve saved Artifact
        uses: actions/download-artifact@v2
        with:
          name: artifact_job2
          path: artifact.txt
      - name: zip artifact
        run: zip artifact.zip artifact.txt
      - name: Upload the zipped artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact.zip
          path: artifact.zip