name: Multiple dependant jobs example
on:
  push:
    branches: [ feature/test ]
  pull_request:
    branches: [ feature/test ]
jobs:
  firstJob:
    runs-on: ubuntu-latest
    steps:
    - name: artifact1
      run: echo "Hello, I'm produced by firstJob" > myArtifact.txt
      uses: actions/checkout@v2
    - name: Upload the artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact1.txt
        path: myArtifact.txt
    - name: Upload the artifact 2
      uses: actions/upload-artifact@v2
      with:
        name: ars/artifact.txt
        path: myArtifact.txt
